### ISSUE TITLE
Share symfony Kernel

### ISSUE THREAD

**Issue by markitosgv** [resquebundle/resque#10]
Do you think is possible to share Symfony kernel booted instead of booting every time a job is processed?

**Comment by tworzenieweb** [comment]
I'm not sure if someone is already working on this but I just started diging into this library and I would say we could set a custom job factory, that not only boot kernel once but also gives the access to dependancy container so then job can have injected dependancies. The only thing that can be tricky / error prone is not to rely on job instance properties or to clean them in teardown section.

**Comment by PhilETaylor** [comment]
over 2 years have moved on, today I released 3.0.0 which has DI built in, but still boots a container/kernel per job. half way there :)
