### ISSUE TITLE
Throttling amount of child workers opened?

### ISSUE THREAD

**Issue by dinbrca** [resquebundle/resque#11]
Hello,
first of all - thank you very much for making the bundle / expanding existing bundles..

I have the following:
a command which runs an Inventory Sync Worker - which in turn runs multiple Product Sync Workers.
Is there any easy way to throttle the amount of opened child workers (Product Sync Workers) within the Inventory Sync Worker until lets say as example 2 (of XX) have finished meaning as long as 2 are still running don't run another one?

Thanks in advance,
Din.

**Comment by PhilETaylor** [comment]
You set the `count` number for the number of workers to run with the command

see: https://github.com/resquebundle/resque/blob/61942e98db72b71d917db8089ac0203c9067df59/Command/StartWorkerCommand.php#L29
