### ISSUE TITLE
ContainerAwareJob getContainer() Broken

### ISSUE THREAD

**Issue by andrewSeldenrust** [resquebundle/resque#25]
I updated composer for a symfony project and one of the 

containerAwareJobs is now throwing a
Resque_Job_DirtyExitException
Job exited with exit code 255

I can boil it down to this line:

`$this->getContainer()->get('doctrine')->getManager` 

I did a little digging and it looks like the 

`$this->kernel->boot(); ` in the abstract class "ContainerAwareJob" is giving the job problems. This is a resqueBundle problem - container works fine outside of the job.  Is there something I could be missing?  Any ideas?  I know I could roll back composer, but I would rather a longer term solution be implemented.  

Thanks,
Andrew

**Comment by PhilETaylor** [comment]
`$this->getContainer()->get('doctrine')->getManager`

should be 

`$this->getContainer()->get('doctrine')->getManager();`

I have no issues with this at all - all my jobs use the container like this

what symfony version?
