### ISSUE TITLE
Incompatible with Symfony 4

### ISSUE THREAD

**Issue by jianzhong** [resquebundle/resque#37]
There are a few places that are not compatible with Symfony version 4.x.

1. bootstrap.php.cache is not available in Symfony4. Therefore app_include is not valid any more, which  affects logic in Configuration.php, ResqueExtension.php, StartWorkerCommand.php, StartScheduledWorkerCommand.php, resque-scheduler and resque.
2. ContainerAwareJob::createKernel throw an error when instantiating Kernel class due to missing a namespace.
3. Autowiring does not appear to work in a job class. Unable to use container->get('aService') even when the service is set to public.

**Comment by PhilETaylor** [comment]
We do not advertise as being compatible with Symfony 4

Please feel free to contribute a PR with fixes for these and I can merge them, personally I have no live projects using Symfony 4 at this time.

**Comment by webignition** [comment]
@PhilETaylor I'm currently migrating a collection of apps to Symfony 4 + flex. I'll get on with working up one or more PRs to address these issues.

Points 1 and 2 above are quite easily resolved by no longer referencing `bootstrap.cache.php` or `app/autoload.php` and instead referencing `vendor/autoload.php`.

Point 3 (service retrieval within a job) I'll need to have a play around with to see what's up.

**Comment by webignition** [comment]
... it would probably have helped if I'd first updated to v 2.0.6 ... points 1 and 2 seem covered there, as for point 3, I've yet to determine if this is an actual issue.

**Comment by webignition** [comment]
@PhilETaylor There are a handful of changes required to get the Symfony flex kernel to boot in `ContainerAwareJob`. 

These changes are not backwards compatible but can he handled with some careful branching.

I'll open a new issue to discuss just that to see where we go from here.

**Comment by PhilETaylor** [comment]
It would be nice to see some progress on this if you have time ?

**Comment by webignition** [comment]
@PhilETaylor I've made great progress for my own personal needs in a fork that I'm now using in production. I'd like to get these changes applied here at some time.

I'll continue such discussion in the #38 as it's more relevant there.

**Comment by PhilETaylor** [comment]
I had need to hack it into symfony 4 last week but in a rush 

I'll be happy to review your fork as a pull request if you have time :)

**Comment by webignition** [comment]
Well, I made some rather broad changes since it was just an experimental fork. There's nothing I could easily pop into any sort of coherent PR.

I'm adding a comment to #38 regarding the creation of branches to help get things heading in the right direction.

**Comment by PhilETaylor** [comment]
Closing as #38 can be used for symfony4 discussion,.
