### ISSUE TITLE
Symfony 4 + Flex kernel creation compatibility

### ISSUE THREAD

**Issue by webignition** [resquebundle/resque#38]
**Overview**
Symfony flex introduces the following changes that impact the ability for `ContainerAwareJob::createKernel()` from being able to work:

- the kernel is namespaced
- environment variables are used to provide application parameters

**Problem 1: kernel namespacing**
`ContainerAwareJob::createKernel()` attempts to find the correct kernel class, includes what is found with a `require_once` and assumes that the kernel's fully-qualified class name (FQCN) matches the kernel file name.

This latter assumption is false under Flex due to the kernel being namespaced.

A overly-complex set of kernel-guessing and error-catching blocks could possibly find the kernel and apply the correct namespace when instantiating. Such a solution is asking for trouble and will eventually fail.

**Problem 2: Environment variables**
Application parameters are provided via environment variables. In production, these are recommended to be defined in the web server config and in development these are recommended to come from a `.env` file. The latter (the `.env` file) is recommended for CLI usage.

Environment variables can be passed to `bin/resque` and this does work, however in production this may well mean needing to define sensitive environment variables within supervisor configuration in addition to however this may already be handled. This again is asking for trouble.

With no environment variables defined and with services dependent on environment variables, `ContainerAwareJob::createKernel()` will fail hard.

**Proposed solution for kernel creation**
Pass a `KERNEL_CLASS` environment variable to `bin/resque` such that `ContainerAwareJob::createKernel()` does not need to guess the kernel class name and won't need to care about what namespace the kernel may or may not live in.

This can be referenced in `ContainerAwareJob::createKernel()` via `$_SERVER['KERNEL_CLASS']` and works just fine.

If `KERNEL_CLASS` is not defined, the current kernel-guessing behaviour can be used.

**Proposed solution for environment variables**
Pass a `USE_DOT_ENV` environment variable to `bin/resque`. If present in  `ContainerAwareJob::createKernel()`, a call will be made to `(new Dotenv())->load(__DIR__.'/../../../.env');` to load environment variables from a local `.env` file. This is how `bin/console` works and this seems a good practice to follow.

**Upcoming PRs**
@PhilETaylor I'll create a PR to handle both of  the above.

**Comment by webignition** [comment]
@PhilETaylor For the reading of `.env` files to work to get environment variables, we'll need to require `symfony/dotenv`. This itself requires `symfony/process` 3.4-ish or 4-ish which means we'd have to drop Symfony 2.8 support going forward.

How do you feel about this?

**Comment by webignition** [comment]
... well, drop all support for Symfony < 3.4 going forwards. There's still the older releases which are just fine, just no new features for Symfony < 3.4.

**Comment by PhilETaylor** [comment]
> How do you feel about this?

I'm happy to maintain a feature frozen version, a 3.4.x version and a 4.x version, I as they all require huge changes, as huge changes have been made in Symfony.

**Comment by webignition** [comment]
@PhilETaylor  Cool, a good starting point would be the creation of some branches and a decision on what goes into what branch. Here's what I suggest.

**Proposed branches**
- `symfony-legacy`
Branched directly off what is currently master (assuming master is stable). This would then represent the state of the code as it is now. This would be the feature-frozen version. Could possibly receive security updates.
- `symfony-3.4`
Initially a branch of current master. Would change through one or more PRs into dropping Symfony 2.x and 4.x support.
- `master` (Symfony 4.x only)

**Proposed releases**
- `2.x`
For releases from the `symfony-legacy` branch.
- `3.x`
For releases from the `symfony-3.4` branch. That the symfony version number and the release major number are similar is coincidental but nice. I went for 3.x since 3 is the next major version for this package.
- `4.x`
For releases from `master`

**PHP version support**
The `symfony-legacy` branch (and `2.x` releases) can continue to have support for legacy PHP versions (5.6). I see no need to change this.

The `symfony-3.4` and `master` branches (and all `3.x` and `4.x` releases) can drop support for legacy PHP versions. Since we get to choose here, I say we put a hard requirement in `composer.json` for PHP >= 7. Support for other PHP versions are still there in the `symfony-legacy` branch.

**Initial changes needed**
- create `symfony-legacy` branch
- create `symfony-3.4` branch
- PR against `symfony-3.4` branch to cut out all of the non-Symfony-3.4 bits and pieces
- release `3.0` off the `symfony-3.4` branch
- PR against `master` to cut out all the non-Symfony-4 bits and pieces (probably just changing the deps in `composer.json` but leaving the code un-fixed at present)
- PR(s) against `master` to drop PHP < 7 (may include upping to newer dev deps like phpunit 7, adding scalar type hints, return type hints and other useful PHP7 features ... probably in a series of PRs to simplify PR reviews)
- PR(s) against `master` for full Symfony 4 compatibility

That's a lot of work to carry out. I can help more if I can be added as a maintainer on the agreement that you get the final say on PRs so as to avoid me messing things up :smiley: 

Otherwise, what do you think? Shall we have those branches created and then go ahead with all of those changes?

**Comment by PhilETaylor** [comment]
Thanks for this - will digest this with coffee when not in the `day job mode`
If only my main project was S4 then I would have more time for this, and the raft of bugs I've discovered in this project since scratching the surface and using it on 20x docker containers in a production environment :-(

**Comment by webignition** [comment]
Reality eh?

**Comment by PhilETaylor** [comment]
This "bundle" is the key component of the project that makes me enough money to buy coffee. I have a huge vested interest in keep it running :-) I just need to get rid of some other non-symfony4 compatible "bundles" before I can get S4 running in this project.

Historically, literally every year, the fall/autumn is the time when I do most code, most major architecture changes throughout all projects, after the "clocks" go back and the sun sets earlier. So I'm betting that will happen again this year.

**Comment by webignition** [comment]
No worries, I understand entirely. I'm happy to continue using my fork for however long is needed.

This bundle is also a key component for me of what brings in the money to pay the bills so I'm more than happy to contribute back when I have the time.

**Comment by broncha** [comment]
I was scratching my head for not being able to boot the Kernel properly. It appreared Kernel booted as expected for the main instance but failed for the child instance. Jobs were being reserved but not completed properly and no error caught.
After some poking around, I figured Kernel boot fails in the forked processes wherever there is a preg_replace call.
Then I found this.
https://github.com/Homebrew/homebrew-core/issues/35491

`pcre.jit=0` in php.ini and everything works fine in SYmfony4, PHP 7.3.7

**Comment by PhilETaylor** [comment]
I have done some major work on this to get up and running in production with Symfony 4.4.0-RC1.

See the new README.md

The main change is that now the actual Job is pulled from the container, and so can have DI into the constructor like it should. 

I've not looked into the flex or namespaced issues, but [the code at release 3.0.0](https://github.com/resquebundle/resque/releases/tag/3.0.0) is now working with no issues in Symfony 4.4.0-RC1 in my production service with 10000s of jobs run a day (mySites.guru)

With that release, Im drawing a line under the ResqueBundle project... and starting from this new base for the future. So closing this issue now, but happy to reopen or receive help/pr's from now on.
