### ISSUE TITLE
PHP Notice on enqueueOnce

### ISSUE THREAD

**Issue by mbourqui** [resquebundle/resque#42]
Hi,

I am using the `enqueueOnce` method, but I get those PHP Notices for this [line](https://github.com/resquebundle/resque/blob/master/Resque.php#L103):

    PHP Notice:  Array to string conversion in [...]/vendor/resquebundle/resque/Resque.php on line 103

But my args are a simple array with strings as keys and values.

What should be done to prevent those notices?

Using:
* PHP 7.2
* Symfony 2.8.49
* resquebundle/resque 2.0.6

**Comment by PhilETaylor** [comment]
Correct. the use of array_intersect on nested arrays [will cause this issue](https://3v4l.org/qn4fN).  :-( 

Please try replacing the enqueueOnce function with this code:

```php
    /**
     * @param Job $job
     * @param bool $trackStatus
     * @return null|\Resque_Job_Status
     */
    public function enqueueOnce(Job $job, $trackStatus = FALSE)
    {
        $queue = new Queue($job->queue);
        $jobs = $queue->getJobs();

        foreach ($jobs AS $j) {
            if ($j->job->payload['class'] == get_class($job)) {

                // remove the retry strategy which is an internal arg
                unset($j->args['resque.retry_strategy']);

                // flatten recursive arrays
                $existingJob = json_encode($j->args);
                $newJob = json_encode($job->args);

                // compare the two strings
                if ($existingJob === $newJob){
                    return ($trackStatus) ? $j->job->payload['id'] : NULL;
                }
            }
        }

        return $this->enqueue($job, $trackStatus);
    }
```

**Comment by PhilETaylor** [comment]
see #43 - I'll try to release this today

**Comment by mbourqui** [comment]
Great, thanks a lot for your quick answer and solution!

I will do the update through composer once the new release is available.

**Comment by PhilETaylor** [comment]
hang on a bit because the current proposed fix is not good enough for my likeing :)

**Comment by PhilETaylor** [comment]
v2.0.9 is now working perfectly.
