### ISSUE TITLE
Deprecations Symfony 4.4

### ISSUE THREAD

**Issue by jellesmets** [resquebundle/resque#52]
Hi there,

First of all, thanks for sharing this nice bundle! I am using this bundle in Symfony 4.4, but I encounter some deprecations:
> Template reference "ResqueBundle::layout.html.twig" not found, did you mean "@Resque/layout.html.twig" in @Resque/Default/index.html.twig at line 1?

When loading the resque homepage. I can fix this by installing the `templating` package, but this is deprecated in Symfony 4.4

Resque commands are extending the `ContainerAwareCommand` class, instead of the Symfony `Command` class and using dependency injection.

I also see some other deprecation messages, but they are related to external packages.

**Comment by PhilETaylor** [comment]
Yes there are some current deprecated features from when I inherited the bundle.

**Comment by PhilETaylor** [comment]
@jellesmets please test the 4.0.0-rc2 release tag

**Comment by jellesmets** [comment]
@PhilETaylor I tested the 4.0.0-rc2 version. The deprecations are resolved now, but now the job fails with following stack trace `#0 /var/www/symfony/vendor/resquebundle/resque/bin/resque(157): Resque_Worker->work()<br>#1 {main}`. The job does not fail in version 3.1.2

**Comment by jellesmets** [comment]
@PhilETaylor The job also fails in the 4.0.0-rc version.

**Comment by jellesmets** [comment]
@PhilETaylor there is a typo in the `StopWorkerCommand` line 54: `$availableWorkers = $rthis->esque->getWorkers();`. Not sure this is related to the above issue though

**Comment by PhilETaylor** [comment]
Thanks for the typo - will get that fixed. 

The other issue is probably related to root_dir/project_dir issues that Im looking into today https://github.com/resquebundle/resque/issues/55 

 The parameter "resque.kernel.root_dir" has a dependency on a non-existent parameter "kernel.root_dir" - it doesn't exist as default in Symfony 5 for some reason.

**Comment by PhilETaylor** [comment]
ok root_dir is a thing of the past - removing all traces of it in favour of Symfony 5 project_dir parameter... see #55
