### ISSUE TITLE
 The parameter "resque.kernel.root_dir" has a dependency on a non-existent parameter "kernel.root_dir".

### ISSUE THREAD

**Issue by PhilETaylor** [resquebundle/resque#55]
```
 The parameter "resque.kernel.root_dir" has a dependency on a non-existent parameter "kernel.root_dir".
```

when installing 4.0.0-rc1 & 4.0.0-rc2

**Comment by PhilETaylor** [comment]
@monofone @jellesmets

Please test 4.0.0-rc3

**NOTE: kernel.root_dir is no longer available in Symfony 5 so this bundle is moving to kernel.project_dir like almost every other bundle is, this means that your kernel needs to be in a sub folder of `%kernel.project_dir%/src/`**

I have checked quite a few Bundles and they all seem to be heading this way. 

To move to version 4 of this bundle you need to update your config yml and change the `resque.root_dir` to be `resque.project_dir` and set it to your projects dir

The bundle will append /src to your path and will look for a Kernel.php in the src folder, or (as in the case of some older projects, in an old bundle folder /src/MyBundle/Kernel.php)

Please test `4.0.0-rc3` after making the above changes. 

There is a new test command that runs `PingJob` with `php bin/console resque:pingtest` to test enqueuing and running Jobs. 

I have tested this ( and now run 4.0.0-rc3) in production and its working for me :) famous last words. 

Let me know your test results and we can push this to stable again.

**Comment by PhilETaylor** [comment]
773010a004c177508ce9ec5b3b58cb2b48c6d91c

**Comment by jellesmets** [comment]
@PhilETaylor The job still fails with the same stack trace message. But when changing `$finder->name('*Kernel.php')->depth(1)->in($this->args['kernel.project_dir'].'/src');` into `$finder->name('*Kernel.php')->depth('<=1')->in($this->args['kernel.project_dir'].'/src');` in `ContainerAwareJob.php`, jobs are processed correctly. As my `kernel.php` file is located in the `src` folder, this change is needed.

**Comment by PhilETaylor** [comment]
Yup you are correct - I have fixed this now in dev-master

**Comment by PhilETaylor** [comment]
v4.0.0 now released.
