### ISSUE TITLE
How to create jobs when it needs dependencies?

### ISSUE THREAD

**Issue by ruudk** [resquebundle/resque#56]
I try to upgrade from a very old version of ResqueBundle to the latest version but I cannot wrap my head around how I should replace ContainerAwareJob.

The readme gives this example job:
```php
<?php

namespace My;

use ResqueBundle\Resque\Job;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\Common\Persistence\ObjectManager;

class MyJob extends Job
{
    /**
     * @var string The queue name
     */
    public $queue = 'myqueue';

    /**
     * @var ManagerRegistry
     */
    private $registry;
    
    /**
     * @var ObjectManager
     */
    private $em;

    /**
     * Use the __construct to inject your dependencies
     *
     * @param array           $args
     * @param ManagerRegistry $registry
     */
    public function __construct(
        $args = [],
        ManagerRegistry $registry
    ) {
        $this->registry      = $registry;
        $this->em            = $registry->getManager();
        parent::__construct($args);
    }

    public function run($args)
    {
        file_put_contents($args['file'], $args['content']);
    }
}
```

Then later explains how to enqueue the job:
```php
// create your job
$job = new MyJob();
$job->args = array(
    'file'    => '/tmp/file',
    'content' => 'hello',
);

// enqueue your job
$resque->enqueue($job);
```

But how can this work? To create a MyJob instance I need to pass `$args = [], ManagerRegistry $registry` to the constructor. 

Does that mean that the example should be like this?

```php
// create your job
$job = new MyJob(
  array(
    'file'    => '/tmp/file',
    'content' => 'hello',
  ),
  $entityManager
);


// enqueue your job
$resque->enqueue($job);
```

**Comment by ruudk** [comment]
Or is the idea that `MyJob` is a service, and in order to enqueue it, I do it like this:
```php
class MyServiceThatEnqueuesJobs
{
    public function __construct(Resque $resque, MyJob $myJob) {
        $this->resque = $resue;
        $this->myJob = $myJob;
    }


    public function doSomething() 
    {
        $this->myJob->args['my args'] = "my value";
        $this->resque->enqueue($this->myJob);
    }
}
```

?

**Comment by PhilETaylor** [comment]
There is some wrapping going on. 

You are not "actually" running the MyJob, you are running `ResqueBundle\Resque\Job` which is container aware, and is passed some args which include rescue.jobclass which is the name of your MyJob class.

Your `MyJob` is passed to that class as `$this->args['resque.jobclass']` and `ResqueBundle\Resque\Job` pulls your MyJob out of the container, giving you full Dependancy Injection :)

**Comment by PhilETaylor** [comment]
Your MyJob class is [pulled out of the container](https://github.com/resquebundle/resque/blob/b8987b95a6094248aa6dd9e831d46b7eb305f77d/Job.php#L64), so $registry (for example) is AutoConfigured :)

**Comment by ruudk** [comment]
So this is how to enqueue jobs?
https://github.com/resquebundle/resque/issues/56#issuecomment-689617081

**Comment by PhilETaylor** [comment]
You do exactly what you used to do... the only changes are under the hood, and you should not be interacting with the container at all, you should be using DI to inject your dependencies using your constructor, after $args as a first parameter

This is all you should need:

```php
// create your job
$job = new MyJob();
$job->args = array(
    'file'    => '/tmp/file',
    'content' => 'hello',
);

// enqueue your job
$resque->enqueue($job);
```

**Comment by ruudk** [comment]
If MyJob's constructor looks like this:
```php
public function __construct(
        $args = [],
        ManagerRegistry $registry
    )
```

How can 
```php
$job = new MyJob();
```
work?

I understand about DI and all. But this is about creating new jobs.

**Comment by PhilETaylor** [comment]
On school run - will dig out my actual working code when I get home

**Comment by PhilETaylor** [comment]
Sorry for the delay, dad mode....

ok my set up is slightly different as I have a frontend server/service that queues jobs, and then a backend/worker server that actually runs the jobs. 

On the frontend server I would have a "job stub" like this

```
<?php

namespace MyJoomlaWorker\Job;

use ResqueBundle\Resque\Job;

/**
 * Class Snapshot.
 */
class Snapshot extends Job
{
    /**
     * Snapshot constructor.
     *
     * @param array $args
     */
    public function __construct($args = [])
    {
        $this->queue = 'snapshot';

        parent::__construct($args);
    }

    /**
     * @param $args
     *
     * @return mixed|void
     */
    public function run($args)
    {
        // Not needed, as workers know how to "run" this job
    }
}
```

and the actual job class on the worker server would look like this:

```php
<?php

namespace MyJoomlaWorker\Job;

use DateTime;
use DateTimeZone;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Persistence\ObjectManager;
use Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ServerException;
use GuzzleHttp\RequestOptions;
use MyJoomlaWorker\Entity\Extensions;
use MyJoomlaWorker\Entity\ExtensionsSite;
use MyJoomlaWorker\Entity\Site;
use MyJoomlaWorker\Entity\Snapshot as SnapshotEntity;
use MyJoomlaWorker\Redis\RedisKeys;
use MyJoomlaWorker\Service\Guzzle;
use MyJoomlaWorker\Service\Remotecall;
use Predis\Client;
use ResqueBundle\Resque\Job;
use ResqueBundle\Resque\Resque;
use stdClass;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * Class Snapshot.
 */
class Snapshot extends Job
{
    /**
     * @var string The queue name
     */
    public $queue = 'snapshot';

    /**
     * @var ManagerRegistry|object|null
     */
    private $doctrine;

    /**
     * @var ObjectManager|object
     */
    private $em;

    /**
     * @var Client
     */
    private $redis;

    /**
     * @var Serializer
     */
    private $serializer;

    /**
     * @var Guzzle
     */
    private $guzzle;

    /**
     * @var Resque
     */
    private $resque;

    /**
     * @var Remotecall
     */
    private $remotecall;

    /**
     * @var CheckForUpdates
     */
    private $checkForUpdates;

    /**
     * @var SSLCheck
     */
    private $SSLCheck;
    private string $pidTitle;

    /**
     * Snapshot constructor.
     *
     * @param array $args
     */
    public function __construct(
        $args = [],
        ManagerRegistry $doctrine,
        Client $redis,
        SerializerInterface $serializer,
        Resque $resque,
        Guzzle $guzzle,
        Remotecall $remotecall,
        CheckForUpdates $checkForUpdates,
        SSLCheck $SSLCheck
    ) {
        $this->doctrine        = $doctrine;
        $this->em              = $doctrine->getManager();
        $this->redis           = $redis;
        $this->serializer      = $serializer;
        $this->resque          = $resque;
        $this->guzzle          = $guzzle;
        $this->remotecall      = $remotecall;
        $this->checkForUpdates = $checkForUpdates;
        $this->SSLCheck        = $SSLCheck;

        $this->pidTitle = cli_get_process_title();

        parent::__construct($args);
    }

    /**
     * @param $args
     *
     * @return mixed|void
     *
     * @throws Exception
     */
    public function run($args)
    {
    	// snip.... but here is a LOT of code :) 
 	}
 }
 ```

What happens when you `enqueue` a job is this:

```php
/**
     * @param Job  $job
     * @param bool $trackStatus
     *
     * @return \Resque_Job_Status|null
     */
    public function enqueue(Job $job, $trackStatus = false)
    {
        if ($job instanceof Job) {
            $job->setKernelOptions($this->kernelOptions);
        }

        $this->attachRetryStrategy($job);
        $this->wrap($job);

        $result = \Resque::enqueue($job->queue, Job::class, $job->args, $trackStatus);

        if ($trackStatus && false !== $result) {
            return new \Resque_Job_Status($result);
        }

        return;
    }
```

This 
1) Checks its a job and sets the kernel options
2) attaches a retry strategy
3) wraps the job, this sets `$args['resque.jobclass'` to have the value of `\get_class($job)` - your job class name
4) uses `Job::class` name, our wrapper class `ResqueBundle\Resque\Job` as the ACTUAL job name that is sent to Resque to queue, our own job name is now buried in the args as resque.jobclass
5) All the rest of the services passed the construct at this point at unused, and abandoned before the Resque adds to the queue

Once the job is pulled out of the queue:
1) the job pulled out of the queue is named `ResqueBundle\Resque\Job` 
2) We extract the $args['resque.jobclass'] value and pull that class from the container - allowing DI to inject all the services passed to the __construct of the job class
3) we run the perform as normal.

 Therefore you are right, if you are using a one server set up, then when you enqueue the job, you are going to have to pass your `$args` as the first param to the __construct of the job, and then also pass in all the dependancies - which are effectivly not used while enqueing the job, but once the job is pulled out of the queue to be processed, then DI will kick in and autowire these extra services for you from the container. 

 The ultimate design was to do away from accessing the container directly, a thing frowned upon now, and to ensure as many deprecated warnings in symfony were removed. 

 Having the job actually pulled out of the container by the `ResqueBundle\Resque\Job` class is how we achieve the Dependancy Injection. 

 Hope this helps. We run literally 1000s of jobs an hour like this and it works well.

**Comment by UgoFlamarion** [comment]
I'm using resquebundle to run detached Symfony commands (I couldn't find another way to do it in a Dockerized environment).
I don't have a frontend and a worker server, I just have a webapp that runs a command when user clicks on a button (or am I missing a key concept here ?).

So what I do right now is using **Process::fromShellCommandline** inside the job to run a command like `php bin/console app:my-command`. But it seems that autowiring is messing up a little bit, more specifically when an autowired parameter in my command is bound to an environment variable.

I tried to put my command's code inside the Job directly, but now just like ruudk I wonder how I can do a `new MyJob()` while having those supposedly autowired services in the constructor. Any idea ?
