### ISSUE TITLE
Release of PHP8 branch?

### ISSUE THREAD

**Issue by LVoogd** [resquebundle/resque#69]
Hi,

Since PHP 8.1  the way this bundle constructs commands is broken. I saw a fix commited to the PHP8 branch but this branch does not have a offical release/tag yet.

When will this branch be released?

Thanks!

**Comment by PhilETaylor** [comment]
https://github.com/resquebundle/resque/releases/tag/5.0.3 and https://github.com/resquebundle/resque/releases/tag/5.0.3 are released from the php8 branch

I no longer use resque in my main income generating project and so this project should be listed now as abandoned or looking for new maintainers.
